GET https://api-skolmi.onrender.com/v1/usersLogin
###
POST https://api-skolmi.onrender.com/v1/login
Content-Type: application/json

{
  "correo": "nico@gmail.com",
  "password": "1234"
}
###
POST  http://localhost:1235/v1/logout
###
POST https://api-skolmi.onrender.com/v1/register
Content-Type: application/json

{
  "nombre": "yonis2",
  "correo": "yonis2@yonis.com",
  "password": "1234",
  "roleId": 1
}
###
GET  http://localhost:1235/v1/users
