POST https://api-skolmi.onrender.com/v1/register
Content-Type: application/json

{
  "nombre": "yonis",
  "correo": "yonis@yonis.com",
  "password": "123",
  "roleId": 1
}
###
GET http://localhost:1235/v1/users
